site_name: party.schieke.eu
site_url: https://party.schieke.eu
site_author: caro und sebe
site_description: infos zur party am 12.9.

theme:
  name: material
  language: de
  font: false

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
